CREATE TABLE users
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(30) NOT NULL UNIQUE,
    password varchar(80) not null,
    email    varchar(50) NOT NULL UNIQUE,
    role     varchar(32) NOT NULL
)