CREATE TABLE categories (
                            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL,
                            description TEXT
);