CREATE TABLE products (
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          description TEXT,
                          price NUMERIC(10, 2) NOT NULL,
                          image VARCHAR(255),
                          category_id BIGINT NOT NULL REFERENCES categories(id),
                          added_date TIMESTAMP,
                          is_active BOOLEAN NOT NULL
);